apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipblocker-app
  namespace: argocd
spec:
  destination:
    namespace: trialnamespace
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kimathimark/ipblocker.git
    targetRevision: master
    path: ip_blocker/k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

