apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crazy-server-ingress
  namespace: trialnamespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: crazy.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crazy-server-service
            port:
              number: 80
